server:
  tomcat:
    port: 8080
    min-spare-threads: 20
    max-threads: 1000
    connection-timeout: 5000

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
